### PR TITLE
fix that typo (not for wax4web, only CLI build)

### PR DESCRIPTION
**Pull request by clockworkindustries-old-old**
fixed ur sh1tty typo ;)

### CODE REVIEW

**Comment by velzie** [comment]
this isn't a typo, and you aren't the first person to make this pull request

the correct term here is "verity" as in dm-verity, the kernel module

**Comment by TheMemeSniper** [comment]
🐟

**Comment by r58Playz** [comment]
:fish:

**Comment by clockworkindustries-old-old** [comment]
image

**Pull request closed without merging**
