### PR TITLE
Update sh1mmer_utilities.sh

### PR DESCRIPTION
**Pull request by MunyDev**
Three letter fix to improve bash shell and fix job control (which can cause issues with certain commands that read from stdin)

### CODE REVIEW

**Comment by MunyDev** [comment]
Sample of the issue:
 Exiting /bin/sh will not work as the enter key is overriden.

**Comment by NotDarkn** [comment]
insane PR

**Review by r58Playz — APPROVED** [review]
:+1:

**Comment by MunyDev** [comment]
Also things like Ctrl c works properly in bash shell

**Comment by MunyDev** [comment]
Will this be merged with main?

**Comment by MunyDev** [comment]
Why is it closed?

**Comment by kxtzownsu** [comment]
based CE, also main is beautifulworld branch lol

**Pull request closed without merging**
