### PR TITLE
remove the "troll" option 

### PR DESCRIPTION
**Pull request by weedgirl68**
what point is there in having a option that lets users unknowingly FORMAT THEIR INTERNAL STORAGE??? this is awful

### CODE REVIEW

**Comment by velzie** [comment]
because it's funny. calm down and enjoy the trolling

**Comment by weedgirl68** [comment]
???

**Comment by JimDude7404** [comment]
Because, its very very obvious its a troll and does no real damage. Just how about dont click it. I find it helpful sometimes to erase evidence so shill your shit

**Comment by velzie** [comment]
local github user does not understand the concept of a joke 😭

**Comment by Scaratek** [comment]
fr keep it

**Comment by TheMemeSniper** [comment]
https://user-images.githubusercontent.com/67394719/219452551-abe06c9f-3a9d-4216-b608-b004928bcde7.mp4

**Pull request closed without merging**
