### PR TITLE
fix "The Fog" button

### PR DESCRIPTION
**Pull request by NotDarkn**
self-explanatory

### CODE REVIEW

**Comment by velzie** [comment]
🐟

**Comment by NotDarkn** [comment]
🐟

**Comment by velzie** [comment]
get rid of jquery

**Comment by NotDarkn** [comment]
> get rid of jquery

can't really make the button work without it, do you want me to just turn it into a file?

**Comment by velzie** [comment]
oh there was jquery in the previous pr too didn't notice sorry i'm going to have to revert that

**Comment by NotDarkn** [comment]
> oh there was jquery in the previous pr too didn't notice sorry i'm going to have to revert that

okay

**Comment by NotDarkn** [comment]
i could also just remove it lol

**Comment by velzie** [comment]
going to revert it in a few hours when i have access to git cli, open a new PR once i do with jquery removed

**Comment by NotDarkn** [comment]
> going to revert it in a few hours when i have access to git cli, open a new PR once i do with jquery removed

done

**Pull request closed without merging**
