### PR TITLE
the most useless github pull request ever

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by TheMemeSniper** [comment]
https://user-images.githubusercontent.com/67394719/216215629-20bc54df-f687-435e-a05d-50bd832c3b84.mov

**Comment by genericness** [comment]
me when the when

**Comment by velzie** [comment]
https://user-images.githubusercontent.com/58010778/216216326-f3796bc5-30f5-4d19-9d9a-69b6eb81a26a.mp4

**Comment by ProgrammerIn-wonderland** [comment]
My god, I'll be honest I forgot we had macOS support since it hasn't been updated forever

**Comment by ghost** [comment]
💀

**Comment by zen1tho** [comment]
computer

**Pull request merged**
