### PR TITLE
Add KVS as an official SH1mmer Legacy Payload.

### PR DESCRIPTION
**Pull request by kxtzownsu**
Add KVS to the official SH1mmer Legacy menu

### CODE REVIEW

**Comment by cloudirector** [comment]
Edging to this pr

**Comment by ThisCatLikesCrypto** [comment]
I converted [the instructions website](https://kvs.kxtz.dev) to what it might look like if it were added to the main sh1mmer one.

https://dev.wilburwilliams.uk/sh1mmer/kvs

**Comment by kxtzownsu** [comment]
@ThisCatLikesCrypto can you change this: 
`A: Both kernver 0 and kernver 1 can downgrade to any version, but kernver 0 doesn't get overriden if you recover to a newer version.` 
to this: 
`A: Both kernver 0 and kernver 1 can downgrade to any version, but theoretically kernver 0 doesn't get overriden on recovery.`

**Comment by velzie** [comment]
the kernvers shouldn't be hardcoded, right now you're making a mess of the filesystem

**Comment by ThisCatLikesCrypto** [comment]
@kxtzownsu i changed the text

**Comment by AverageJuliet** [comment]
closed because koaku didn't comment

**Comment by psmpm** [comment]
pr closed

**Comment by ProgrammerIn-wonderland** [comment]
Don't feel like it

**Comment by NotDarkn** [comment]
rip 🗿

**Comment by MadjikDotPng** [comment]
Comment

**Comment by psmpm** [comment]
oop, koaku commented seemingly to get the pr to not be merged.
LGTM

**Comment by psmpm** [comment]
okay nevermind i looked at the code and this is garbage, despite koaku trying to get this not merged i will have to agree

**Comment by WeirdTreeThing** [comment]
Two copies of each kernver 😭

**Comment by genericness** [comment]
> okay nevermind i looked at the code and this is garbage, despite koaku trying to get this not merged i will have to agree

just took a look due to boredom and can agree

**Comment by kxtzownsu** [comment]
ok well im sorry i cant optimize every little thing because i have better shit to do in my life then work on a **side project**

**Pull request closed without merging**
